services:
  party-games:
    image: "localhost/paper-minecraft-server"
    volumes:
      - "./data/party-games/server:/server"
    networks:
      - main
    ports:
      - "25565:25565"
  missile-wars:
    image: "localhost/paper-minecraft-server"
    volumes:
      - "./data/missile-wars:/server"
    networks:
      - main
      - mw
    ports:
      - "25566:25565"
networks:
  main:
    driver: bridge
  mw:
    driver: bridge
