services:
  bungee:
    image: "bungee:latest"
    networks:
      - main
    ports:
      - "25565:25565"
  missile-wars:
    image: "localhost/missile-wars:latest"
    networks:
      - main
    ports:
      - "25566:25566"
networks:
  main:
    driver: bridge
